---
- name: Deploy and Restart Services
  hosts: all
  become: true
  tasks:
    - name: Stop server systemd daemon
      systemd:
        name: xmr-nodes-server.service
        state: stopped
      when: inventory_hostname in groups['server']

    - name: Upload binary file
      copy:
        src: ../../bin/xmr-nodes-static-linux-amd64
        dest: /path/to/remote/server/bin
        Owner: your_user
        Group: your_group
        mode: 0755

    - name: Start systemd daemon
      systemd:
        name: xmr-nodes-server.service
        state: started
      when: inventory_hostname in groups['server']
