linters-settings:
  errcheck:
    ignore: ""

issues:
  exclude-rules:
    - path: frontend/embed.go
      text: "pattern build/\\*: no matching files found"
    - path: _test.go
      linters:
        - errcheck
