on:
  push:
    branches:
      - main
      - htmx

  pull_request:
name: Test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Setup templ
        run: go install github.com/a-h/templ/cmd/templ@v0.2.778

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Prepare assets
        run: make prepare templ tailwind

      - name: Run lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Run test
        run: make test
